### ISSUE TITLE
Pug "Include" tag not working

### ISSUE THREAD

**Issue by migbash** [Wscats/compile-hero#19]
Issue explained on [stackoverflow](https://stackoverflow.com/questions/61956779/trouble-using-include-with-a-pug-file?noredirect=1#comment109587642_61956779).

I have tried everything, but it appears to be an issue with the compile-hero itself, as when compiling a .pug file manually:

`const pug = require('pug');
console.log(pug.renderFile('wallet_ui.pug'));`

Everything works perfectly.

**Comment by Markuvines** [comment]
Same problem

**Comment by Wscats** [comment]
Thank you for your feedback, I debug the code to solve😁 @Markuvines @migbash

**Comment by Wscats** [comment]
![Kapture 2020-05-23 at 7 49 02](https://user-images.githubusercontent.com/17243165/82716570-b90a2c80-9cca-11ea-92cf-79e61581b6a2.gif)

Fix compilation failure due to relative path of pug😁 @Markuvines  @migbash 

If you think it's useful, you can leave us a [message and like it](https://marketplace.visualstudio.com/items?itemName=Wscats.qf&ssr=false#review-details), Your support is our driving force😀
